<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IG_Ikon</name>
   <tag></tag>
   <elementGuidId>bf6b0840-44b2-4870-85ae-d1edc99397e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fab.fa-youtube</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div/div/div/div[3]/div/a[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>560886a0-c91d-4c9f-84d5-a81e57c8b545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fab fa-youtube</value>
      <webElementGuid>7ebfcc6a-0812-48ec-b6c3-03a1dafea0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[@class=&quot;footer-half sub-bg section-padding pb-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5&quot;]/div[@class=&quot;cont&quot;]/div[@class=&quot;social-icon&quot;]/div[@class=&quot;social&quot;]/a[@class=&quot;icon&quot;]/i[@class=&quot;fab fa-youtube&quot;]</value>
      <webElementGuid>58b467e6-1519-4a5a-8588-8b10557c1cff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div/div/div/div[3]/div/a[4]/i</value>
      <webElementGuid>4de3edfc-df3b-46e3-b311-7ff02f1f44df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>9c5e7a93-5d44-4453-b481-c697c2683766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div/div/div/div[3]/div/a[2]/i</value>
      <webElementGuid>1257c2d9-46ad-4e12-9772-142369b4d162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>856db6a2-2ed8-4944-b7ff-951c5fdcebd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
