<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>geser_kanan</name>
   <tag></tag>
   <elementGuidId>b005137c-4171-4bbb-990e-23b4c12b0259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-chevron-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/header/div/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cf4bb093-171d-4c46-9dee-768fcbff8684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-chevron-right</value>
      <webElementGuid>a932790e-59d2-4ccb-bd4a-2908a8152f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[@class=&quot;slider slider-prlx fixed-slider text-center&quot;]/div[@class=&quot;swiper-container parallax-slider&quot;]/div[@class=&quot;setone setwo&quot;]/div[@class=&quot;swiper-button-next swiper-nav-ctrl next-ctrl cursor-pointer&quot;]/i[@class=&quot;fas fa-chevron-right&quot;]</value>
      <webElementGuid>6edd0dd5-4647-40b0-8201-eb3a6e125eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div/div[2]/div/i</value>
      <webElementGuid>0e93cb5f-20ea-4ab2-ae3e-5658a3620f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>857ce919-54e8-4d0b-8f1d-68e249986601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
