<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lokasi_kantor</name>
   <tag></tag>
   <elementGuidId>2fd7f019-5419-4bea-a5ce-2862ee077291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.con-info > ul > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/footer/div/div/div/div/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>60eeae9a-97fb-4f35-8943-22b6ac2c986f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://goo.gl/maps/dGE8TUNt6ziYc6sN6</value>
      <webElementGuid>e275d5a3-6a04-4bc0-8221-6c73566b0c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Abdul Hakim, Komp. Classical Setiabudi Residence II Blok A No. 1, Pasar Satu - Tanjung Sari, Kota Medan, Sumatera Utara 20131</value>
      <webElementGuid>a8cbe56e-0566-49fa-b748-83e68af22e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;main-content&quot;]/footer[@class=&quot;footer-half sub-bg section-padding pb-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5&quot;]/div[@class=&quot;cont&quot;]/div[@class=&quot;con-info&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>64503e13-41ba-4bb5-88af-f64ddf253d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/footer/div/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>fbb0608d-d5a4-4201-94f9-d570ffe0e1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jl. Abdul Hakim, Komp. Classical Setiabudi Residence II Blok A No. 1, Pasar Satu - Tanjung Sari, Kota Medan, Sumatera Utara 20131')]</value>
      <webElementGuid>293a63d2-5550-4661-b6ac-946e26ca5143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/following::a[1]</value>
      <webElementGuid>ef1c3aee-7fa4-4c69-9b99-535824a83702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Office'])[1]/following::a[1]</value>
      <webElementGuid>faf2f041-73ce-44f1-bef6-70c74de63d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workshop'])[1]/preceding::a[1]</value>
      <webElementGuid>d998bf02-607e-42f1-a130-ff8fee568873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/preceding::a[1]</value>
      <webElementGuid>b6a05401-3e51-45bf-befa-0a4ce247b514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl. Abdul Hakim, Komp. Classical Setiabudi Residence II Blok A No. 1, Pasar Satu - Tanjung Sari, Kota Medan, Sumatera Utara 20131']/parent::*</value>
      <webElementGuid>5389cfa3-d5a5-4906-be0d-c24d912de86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://goo.gl/maps/dGE8TUNt6ziYc6sN6')]</value>
      <webElementGuid>059e1c01-1829-47dd-99f4-b1a596db4556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>55e18e58-39b6-4c76-93cf-80861aa3cb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://goo.gl/maps/dGE8TUNt6ziYc6sN6' and (text() = 'Jl. Abdul Hakim, Komp. Classical Setiabudi Residence II Blok A No. 1, Pasar Satu - Tanjung Sari, Kota Medan, Sumatera Utara 20131' or . = 'Jl. Abdul Hakim, Komp. Classical Setiabudi Residence II Blok A No. 1, Pasar Satu - Tanjung Sari, Kota Medan, Sumatera Utara 20131')]</value>
      <webElementGuid>4465b919-26c3-42a2-b509-86ed648c688a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
