<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lokasi_workshop</name>
   <tag></tag>
   <elementGuidId>c48963a8-dbc5-4e7c-82b3-9578c558b678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.con-info > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/footer/div/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3c51a4a-1ecd-4ba9-b16a-4635d7def939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://goo.gl/maps/sHRJJq28LAjFgYDb8</value>
      <webElementGuid>4c7c0bd6-323f-4c07-b3ce-55d6cbd2215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Bunga Terompet Sempakata No. 10-11, Medan Selayang, Medan Sumatera Utara 20132</value>
      <webElementGuid>3dee966f-22ce-4650-a437-bade9a803a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;main-content&quot;]/footer[@class=&quot;footer-half sub-bg section-padding pb-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5&quot;]/div[@class=&quot;cont&quot;]/div[@class=&quot;con-info&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>f821fac0-cef2-436f-b605-b0680ff9b6b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/footer/div/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>c43d024c-2175-4356-964a-de8ef75fa23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jl. Bunga Terompet Sempakata No. 10-11, Medan Selayang, Medan Sumatera Utara 20132')]</value>
      <webElementGuid>a40c105d-8d97-429a-8e35-9183635f6528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/following::a[1]</value>
      <webElementGuid>f9d878ef-1e88-4071-952f-683fe2253d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workshop'])[1]/following::a[1]</value>
      <webElementGuid>fa1a812f-0925-4d67-b212-245328e2197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::a[1]</value>
      <webElementGuid>5720d7f2-0e49-42db-9792-4ae5dea5e08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[4]/preceding::a[1]</value>
      <webElementGuid>9755f8c0-c000-4792-9d4a-905ee7313e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl. Bunga Terompet Sempakata No. 10-11, Medan Selayang, Medan Sumatera Utara 20132']/parent::*</value>
      <webElementGuid>70eb5705-d38f-4fa7-8346-ea7f58be6f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://goo.gl/maps/sHRJJq28LAjFgYDb8')]</value>
      <webElementGuid>8d88b547-7cce-44d1-9bef-809ef46bd606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>a8013659-b336-4181-b8f2-05c4fabdd799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://goo.gl/maps/sHRJJq28LAjFgYDb8' and (text() = 'Jl. Bunga Terompet Sempakata No. 10-11, Medan Selayang, Medan Sumatera Utara 20132' or . = 'Jl. Bunga Terompet Sempakata No. 10-11, Medan Selayang, Medan Sumatera Utara 20132')]</value>
      <webElementGuid>ade0d79e-b045-40be-b90a-e0646db2cb37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
